//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_picecMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catr
    {
        public int id_cart { get; set; }
        public Nullable<int> id_proudect { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual proudect proudect { get; set; }
        public virtual USER USER { get; set; }
    }
}
