//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_picecMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_id { get; set; }
        public string Comment_text { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> Proudect_id { get; set; }
    
        public virtual proudect proudect { get; set; }
        public virtual USER USER { get; set; }
    }
}
